/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.Icon;
import javax.swing.JList;

/**
 *
 * @author OMAR
 */
public class Ayuda extends javax.swing.JFrame {

    /**
     * Creates new form Ayuda
     */
    public Ayuda() {
        initComponents();
        jLabelMovimiento.setText("");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaAyuda = new javax.swing.JList();
        panelOpcionesAyuda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextAreaInformacionAyuda = new javax.swing.JTextArea();
        jLabelMovimiento = new javax.swing.JLabel();
        jLabelAyuda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 153));

        jPanel1.setBackground(new java.awt.Color(0, 255, 153));

        listaAyuda.setBackground(new java.awt.Color(102, 255, 51));
        listaAyuda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaAyuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaAyuda.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Reglas del Juego", "Movimiento de Pollo", "Movimiento de Pollo eterno", "Movimiento de Cocodrilo", "Movimiento de Humano", "Movimiento de Godzilla" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaAyuda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaAyuda.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaAyudaValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listaAyuda);

        panelOpcionesAyuda.setBackground(new java.awt.Color(255, 204, 153));
        panelOpcionesAyuda.setPreferredSize(new java.awt.Dimension(100, 100));

        jScrollPane1.setAutoscrolls(true);

        jtextAreaInformacionAyuda.setEditable(false);
        jtextAreaInformacionAyuda.setBackground(new java.awt.Color(204, 204, 204));
        jtextAreaInformacionAyuda.setColumns(20);
        jtextAreaInformacionAyuda.setRows(5);
        jtextAreaInformacionAyuda.setAutoscrolls(false);
        jScrollPane1.setViewportView(jtextAreaInformacionAyuda);

        jLabelMovimiento.setText("imagen de movimiento de jugadores");

        javax.swing.GroupLayout panelOpcionesAyudaLayout = new javax.swing.GroupLayout(panelOpcionesAyuda);
        panelOpcionesAyuda.setLayout(panelOpcionesAyudaLayout);
        panelOpcionesAyudaLayout.setHorizontalGroup(
            panelOpcionesAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesAyudaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelOpcionesAyudaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        panelOpcionesAyudaLayout.setVerticalGroup(
            panelOpcionesAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesAyudaLayout.createSequentialGroup()
                .addGroup(panelOpcionesAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcionesAyudaLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2))
                    .addGroup(panelOpcionesAyudaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelAyuda.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelAyuda.setForeground(new java.awt.Color(255, 0, 0));
        jLabelAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ayuda.jpg"))); // NOI18N
        jLabelAyuda.setText("AYUDA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelAyuda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelOpcionesAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelOpcionesAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaAyudaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaAyudaValueChanged
        boolean adjust=evt.getValueIsAdjusting();
        jLabelMovimiento.setIcon(null);
        jLabelMovimiento.setVisible(true);
        jtextAreaInformacionAyuda.setText("");
        
        this.repaint();
        this.pack();
        if (!adjust) {
            JList lsm=(JList)evt.getSource();
            int seleccionado=lsm.getSelectedIndex();
            switch(seleccionado){
                case 0:
                    jLabelMovimiento.setVisible(false);
                   jScrollPane1.setVisible(true);
                    jtextAreaInformacionAyuda.setVisible(true);
                    jtextAreaInformacionAyuda.setText("REGLAS\n-------------------------\n"
                  + "GANADOR: El jugador que coma a godzilla del otro oponente sera el ganador\n"
                  + "Jugadores: Pollo, Godzilla, Humano, Cocodrilo\n"
                  + "Empieza el juego con el jugador A");
                    
                   //jtextAreaInformacionAyuda.setSize(panelOpcionesAyuda.getWidth()-5,panelOpcionesAyuda.getHeight()-5);
                   //jScrollPane1.setSize(panelOpcionesAyuda.getWidth()-5,panelOpcionesAyuda.getHeight()-5);

                   this.pack();
//                    + "Hay 2 formas de ingresar las fechas\n"
//                    + "\t1.Se debe escribir en el campo de las fechas\n"
//                    + "\t2.hacer clic en el boton de fecha para elegirla\n"+
//                    "Seleccionar Cliente:\n\tPermite seleccionar un cliente realizandose asi una busqueda\n"+
//                    "Verificar:\n\tSe comprobara si la habitacion esta disponible o no"

                break;
                case 1:
                     
                   jLabelMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movimiento_pollo.jpg")));
                   
                     //txtAreaAyuda.setText("AYUDA ADMINISTRAR RESERVA\n-------------------------\n"
//                    + "En esta opcion se podra seleccionar la fecha en la cual se verá\n"
//                    + "el listado de reservas cada una de estas puede ser modificada\n"
//                    + "como tambbien cancelada(eliminada)\n");
                    jScrollPane1.setVisible(false);
                    
                    jtextAreaInformacionAyuda.setVisible(false);
                    this.pack();
                break;
                case 2:
                    jLabelMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movimiento_pollo_inmortal.jpg")));
                    jScrollPane1.setVisible(false);
                    jtextAreaInformacionAyuda.setVisible(false);
                    this.pack();
                    
//                    txtAreaAyuda.setText("CONSULTAS Y/O DUDAS\n-------------------------\n"
//                    + "Escribir al sgte. correo: teatroAyuda@gmail.com\n"
//                    + "O llamar al sgte número: 966666666");
                break;
                case 3:
                    jLabelMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movimiento_cocodrilo.jpg")));
                    jScrollPane1.setVisible(false);
                    jtextAreaInformacionAyuda.setVisible(false);
                    this.pack();
                    break;    
                case 4:
                    jLabelMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movimiento_humano.jpg")));
                    jScrollPane1.setVisible(false);
                    jtextAreaInformacionAyuda.setVisible(false);
                    this.pack();
                    break;   
                case 5:
                    jLabelMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movimiento_godzilla.jpg")));
                    jScrollPane1.setVisible(false);
                    jtextAreaInformacionAyuda.setVisible(false);
                    this.pack();
                    break; 
                default: break;
            }
        }
//        else txtAreaAyuda.setText("");
    }//GEN-LAST:event_listaAyudaValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ayuda().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAyuda;
    private javax.swing.JLabel jLabelMovimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jtextAreaInformacionAyuda;
    private javax.swing.JList listaAyuda;
    private javax.swing.JPanel panelOpcionesAyuda;
    // End of variables declaration//GEN-END:variables
}
