/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Vistas.Tablero.TableroGUI;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.GroupLayout;
import javax.swing.JLabel;

/**
 *
 * @author OMAR
 */
public class Juego extends javax.swing.JPanel {
    private JuegoPrincipal juegoPrincipal;
    private TableroGUI tableroGUI;
    /**
     * Creates new form Juego
     */
    public Juego() {
       initComponents();
        tableroGUI=new TableroGUI(5,8,true);
        myInitComponents();
    }

    public Juego(JuegoPrincipal juegoPrincipal) {
        //initComponents();
        this.juegoPrincipal=juegoPrincipal;
        tableroGUI=new TableroGUI(5,8,true);
        myInitComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAtras = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 153));

        labelAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.jpg"))); // NOI18N
        labelAtras.setToolTipText("Volver atras");
        labelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Juego.this.mousePressed(evt);
            }
        });

        jLabel6.setText("VIDA SALVAJE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel6)
                .addGap(123, 123, 123)
                .addComponent(labelAtras)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed
        
        juegoPrincipal.remove(jLabel6);
        juegoPrincipal.remove(labelAtras);
        juegoPrincipal.remove(this);
        juegoPrincipal.remove(tableroGUI);
        juegoPrincipal.setLayout(new FlowLayout());
        juegoPrincipal.add(new MenuJuego(juegoPrincipal),BorderLayout.CENTER);
        juegoPrincipal.pack();
        juegoPrincipal.setLocationRelativeTo(null);
    }//GEN-LAST:event_mousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelAtras;
    // End of variables declaration//GEN-END:variables

    private void myInitComponents() {
        jLabel6=new JLabel();
        labelAtras=new JLabel();
        jLabel6.setText("Vida Salvaje");
        setBackground(new java.awt.Color(0, 255, 153));
        javax.swing.GroupLayout tableroGUILayout = new javax.swing.GroupLayout(tableroGUI);
        tableroGUI.setLayout(tableroGUILayout);
        tableroGUILayout.setHorizontalGroup(
            tableroGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0,700, Short.MAX_VALUE)
        );
        tableroGUILayout.setVerticalGroup(
            tableroGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        
        

        labelAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.jpg"))); // NOI18N
        labelAtras.setToolTipText("Volver atras");
        labelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Juego.this.mousePressed(evt);
            }
        });

        
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(juegoPrincipal.getContentPane());
        juegoPrincipal.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(30, Short.MAX_VALUE))
             
             .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableroGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelAtras)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)//Definimos tamaño del Label
                .addGap(20)
                .addComponent(tableroGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(labelAtras)
                .addGap(30)
                )
        );
        //juegoPrincipal.pack();
        
        
    }
}
